name: RSS → Notion

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ingest RSS → Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
          MAX_ITEMS_PER_FEED: ${{ secrets.MAX_ITEMS_PER_FEED }}
          ALLOW_UPDATES: ${{ secrets.ALLOW_UPDATES }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: |
          python src/rss_to_notion.py
